apiVersion: v1
kind: Pod
metadata:
  labels:
    app: employees
  name:  app
spec:
  containers:
    - name: app
      image: 293969756141.dkr.ecr.us-east-1.amazonaws.com/assignment2_repo_app:v2.0
      ports:
        - containerPort: 8080
          protocol: TCP
      env:
        - name: DBHOST
          value: "10.244.0.5"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "clo825_2"
        - name: DBPORT
          value: "3306"