apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mysqlserver
  name: mysql
spec:
  containers:
    - name: mysql
      image: 293969756141.dkr.ecr.us-east-1.amazonaws.com/assignment2_repo_db:v2.0
      ports:
       - containerPort: 3306
         protocol: TCP

      env:
       - name: MYSQL_ROOT_PASSWORD
         value: "clo825_2"
